[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/segmentio/kafka-go"
  version = "0.3.6"

[[constraint]]
  name = "gopkg.in/linkedin/goavro.v2"
  version = "2.9.8"

[[constraint]]
  name = "github.com/loadimpact/k6"
  version = "0.26.2"
